AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket on LocalStack.

Resources:
  VGIStepFunctionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vgi-step-functions-scheduler

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref VGIStepFunctionsBucket
